const Config = {
    debug: true,
    svgWidth: window.innerWidth - 16,
    svgHeight: 1000,
    evenRowsColor: '#efeff4',
    oddRowsColor: '#dddddf',
    rowEdgeColor: 'transparent',
    levelPadding: 16,
    textPaddingX: 8,
    textPaddingY: 6,
    wordPadding: 4,
    edgePadding: 10,
    rowPadding: 30,
    hideLinkLinesPercentage: 3.0, //percentage at which links and arrows are hidden
    hideLinkTextPercentage: 7.0, //percentage at which words are link words are hidden
    handleW: 10,
    handleH: 16,
    handleColor: '#ff0000',
    handleOpacity: 0.1,
    arrowH: 5,
    arrowMH: 5,
    arrowW: 3,
    wordHeight: 16,
    minWordWidth:25,
    evenRowsColor_selected: '#cdcdff',
    oddRowsColor_selected: '#bbbbff',
    dragRectSide: 8,
    dragRectMargin: 1,
    dragDir: 0,
    linkStrokeThickness: 1.5,
    linkStrokeColor: '#cc9999',
    linkStrokeOpacity: 1,
    linkStrokeThickness_selected: 1.5,
    linkStrokeColor_selected: '#449944',
    linkStrokeOpacity_selected: 1.0,
    attachmentMargin: 0.1,
    word2word_strategy: strategies.FARTHEST,
    word2link_strategy: strategies.CLOSEST, 
    link2link_strategy: strategies.FARTHEST //CLOSEST sometimes causes overlaps - need to be a bit more rigorous when assigning slots - don't assign any slots that have the potential to overlap (when dragged manually)? - or let the buyer beware that this could happen - they can always move out of the way - right now it won't automatically overlap, but won't prevent a user from doing it. 
};